### ISSUE TITLE
Can't add to Chrome, requires updating to manifest v3

### ISSUE THREAD

**Issue by stevenhuyn** [yankeexe/12ft-browser-extension#1]
Hey thanks for the extension!

Wasn't able to load it.
![image](https://user-images.githubusercontent.com/18359644/170167774-f08b9719-6580-4dc3-a31c-a8b67183e473.png)

I have a fork where I've updated it.

Let me know if you are accepting Pull Requests!

**Comment by yankeexe** [comment]
@stevenhuyn yes accepting Pull Requests! 
Let's upgrade it to manifest v3!

**Comment by stevenhuyn** [comment]
Yep made a PR @yankeexe
