### ISSUE TITLE
Doesn't work on Firefox.

### ISSUE THREAD

**Issue by aminomancer** [yankeexe/12ft-browser-extension#3]
Firefox doesn't support service worker background scripts.

**Comment by aminomancer** [comment]
Looks like in order to support both Chrome and Firefox, you would need to maintain 2 versions. There are tools for this sort of thing, like [parcel](https://parceljs.org/recipes/web-extension/) (setting up two targets to build). I got the extension to work by making the following changes:

```udiff
diff --git a/background.js b/background.js
index 2bd733ed561a2..fe24b77a596ee 100644
--- a/background.js
+++ b//background.js
@@ -1,4 +1,4 @@
-chrome.action.onClicked.addListener(() => {
+chrome.browserAction.onClicked.addListener(() => {
   chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
     const url = new URL(tabs[0].url)
 
diff --git a/manifest.json b/manifest.json
index be8065627e379..f9092e981b740 100644
--- a/manifest.json
+++ b/manifest.json
@@ -1,14 +1,26 @@
 {
   "name": "12ft",
+  "short_name": "12ft",
   "description": "Remove Paywalls using 12ft ladder",
-  "version": "0.6",
+  "version": "0.4",
   "author": "Yankee Maharjan",
-  "manifest_version": 3,
+  "manifest_version": 2,
+  "browser_specific_settings": {
+    "gecko": {
+      "id": "12ft@yankeemaharjan"
+    }
+  },
   "background": {
-      "service_worker": "background.js"
+      "scripts": ["background.js"],
+      "persistent": false
   },
   "permissions": ["activeTab"],
-  "action": {
+  "icons": {
+    "16": "assets/16x16.png",
+    "48": "assets/48x48.png",
+    "128": "assets/128x128.png"
+  },
+  "browser_action": {
       "default_icon": {
           "16": "assets/16x16.png",
           "48": "assets/48x48.png",
```

**Comment by yankeexe** [comment]
Hey @aminomancer thank you for reporting; if you are available, would appreciate a PR for this change. 🙂

**Comment by aminomancer** [comment]
I would, but I'm not sure of the best way to do this without breaking the Chrome version. I see a previous PR covering the issue that Chrome no longer supports MV2. So, we're kinda between a rock and a hard place 😅

That's why I like the idea of using a bundler to build 2 different versions. But you gotta be sure the local environment is working for you, so you can build it yourself in the future. I've used parcel for node modules and web apps, but I've only just read about using it for webextension transpilation. Parcel does have great documentation though. And [following this](https://www.samdawson.dev/article/parceljs-chrome-extension) would probably help. I'm happy to answer any questions, if I can.

The simplest possible way of doing this is, I think, by setting up a file structure like
```
project
├─ package.json
├─ .parcelrc
├─ src/
│  ├─ chrome/
│  │  ├─ manifest.json
│  │  └─ background.js
│  ├─ fx/
│  │  ├─ manifest.json
│  │  └─ background.js
│  ├─ static/
│  │  └─ assets/...
└─ dist/
   ├─ chrome/
   │  ├─ manifest.json
   │  ├─ background.js
   │  └─ assets/...
   └─ fx/
      └─ package.zip
         ├─ manifest.json
         ├─ background.js
         └─ assets/...
```
And then in package.json, you have something like this
```
  "targets": {
    "chrome": {
      "source": "./src/manifest-chrome.json",
      "distDir": "./dist/chrome/"
    },
    "fx": {
      "source": "./src/manifest-fx.json",
      "distDir": "./dist/fx/"
    }
  },
```
And use [this config](https://parceljs.org/recipes/web-extension/), plus some kind of namer plugin to get the generic names. It's a bit complicated I guess, but you could look through the repos of some other popular webextensions to see how they do it.

**Comment by yankeexe** [comment]
@aminomancer looks good. I will give the articles and docs you have linked a read.
For one of my other extension, I have just built support for both Chrome and Firefox this:
https://github.com/yankeexe/github-code-editors

**Comment by aminomancer** [comment]
Looks like a neat extension!

- Shane

**Comment by yankeexe** [comment]
@aminomancer 
New support for Firefox has been release: 
https://github.com/yankeexe/12ft-browser-extension/releases/tag/0.7

**Comment by aminomancer** [comment]
Thanks for working on this!
Unfortunately it still doesn't work. Firefox requires a key:
```json
  "browser_specific_settings": {
    "gecko": {
      "id": "12ft@yankeemaharjan"
    }
  }
```
